---
title: Using the EdSurvey Package to Analyze NAEP Data With and Without Accommodations
author: Ahmad Emad, Michael Lee, Huade Huo, Ting Zhang, Qingshu Xie, & Jiao Yu\footnote{This publication was prepared for NCES under Contract No. ED-IES-12-D-0002 with American Institutes for Research. Mention of trade names, commercial products, or organizations does not imply endorsement by the U.S. Government.} \footnote{The authors would like to thank Paul Bailey and Dan Sherman for reviewing this document.}
date: '`r format(Sys.Date(),"%B %d, %Y")`'
output:
  pdf_document:
    fig_caption: yes
    number_sections: no
# bibliography: edsurvey.bib
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{3. Accommodations in NAEP}
  \usepackage[utf8]{inputenc}
---

# Background
Prior to 1996, the National Assessment of Educational Progress (NAEP) did not allow accommodations for students with disabilities (SD) and English language learners (ELL). Since 2002, NAEP has provided accommodations for all students who need them. In the transition period, student samples in each NAEP assessment were split between two test settings in which accommodations were either allowed in the assessment or not allowed, with the purposes of maintaining data trends to the past, studying the impact of accommodations on NAEP results, and beginning new trend baselines with accommodations.

These samples in the two test settings were combined into one data set for selected years. This vignette explains how such data sets can be analyzed using the `EdSurvey` package.

# Overview
The National Center for Education Statistics (NCES) provides an [overview of the inclusion of Special-Needs Students](https://nces.ed.gov/nationsreportcard/about/inclusion.aspx) in the NAEP.

> Accommodations in the testing environment or administration procedures are provided for SD and ELL students. Examples of accommodations permitted by NAEP are extra time, testing in small-group or one-on-one sessions, reading aloud to a student, and scribing a student's responses. Examples of testing accommodations not allowed include adminstering the reading assessment in a language other than English or reading the reading passages aloud to the student. (NCES 2014)

In the development of stand-alone assessments, NAEP used a split-sample design to measure the impact of accommodations for special-needs students. Based on the split-sample design, there were essentially two separate samples based on the settings for testing accommodations. In some of the sampled schools, accommodation were not permitted for students with SD and students classified as ELL; in other sampled schools, accommodations were permitted for SD and ELL students. In years listed in Table 1, each assessment consists of two assessment samples: one with accommodations permitted, and the other with accommodations not permitted. As a result, there may be two separate data sets for reporting assessment results based on whether accommodations were permitted or not. The data for assessment with no accommodations permitted include the students from both samples in the two test settings who were not identified as SD and ELL and the SD and ELL students assessed with no accommodations. The data for assessment with accommodations permitted include the students from both samples in the two test settings who were not identified as SD and ELL and the SD and ELL students assessed with accommodations. The two reporting samples usually are combined into one data set, with two separate sets of key variables such as weights and plausible values for reporting accommodations-not-permitted and for accommodations-permitted assessment results, respectively.

\newpage

*Table 1. NAEP data with split-sample design for accommodations, by year, grade, and subject*

| Subject     | Grade | Split-sample design year(s)|
|-------------|-------|----------------------------|
| Geography   | 4     | 2001                       |
| Geography   | 8     | 2001                       |
| Geography   | 12    | 2001                       |
| History     | 4     | 2001                       |
| History     | 8     | 2001                       |
| History     | 12    | 2001                       |
| Mathematics | 4     | 1996, 2000                 |
| Mathematics | 8     | 1996, 2000                 |
| Mathematics | 12    | 1996, 2000                 |
| Reading     | 4     | 1998, 2000                 |
| Reading     | 8     | 1998                       |
| Reading     | 12    | 1998                       |
| Science     | 4     | 1996, 2000                 |
| Science     | 8     | 1996, 2000                 |
| Science     | 12    | 1996, 2000                 |

SOURCE: U.S. Department of Education, Institute of Education Sciences, National Center for Education Statistics, National Assessment of Educational Progress (NAEP), NAEP Data Explorer

# Using the `EdSurvey` package to analyze data with accommodations
For these years with both samples, `RPTSAMP=1` indicates the sample for the assessment in which accommodations were not permitted, and `ARPTSMP=1` indicates the sample for the assessment in which accommodations were permitted. When both `RPTSAMP` and `ARPTSMP` are available, the default behavior for `EdSurvey` is to use the sample with accommodations not permitted (e.g., `RPTSAMP=1`).

To use the sample with accommodations permitted with `EdSurvey` functions (e.g., `lm.sdf`, `cor.sdf`, `achievementLevels`), you may want to follow these steps:

1. `Subset` the data with condition `ARPTSMP==1` before conducting your analysis.
2. Please make sure to set `defaultConditions=FALSE`, as `defaultConditions` subsets data to `RPTSMP==1` by default.
3. Specify the weight for accommodations-permitted data: `weightVar="aorigwt"`.
4. Use "composite_ap" for analysis with plausible values. The "composite_ap" argument represent the variables for the composite plausible values for the accommodation-permitted assessment reporting sample.

In the example below, the data set `math4` is subset where `ARPTSMP==1`. This new subsample of the data set (saved as `math4a`) is then used to calculate achievement levels with accommodation-permitted data.

```{r read accommodation permitted, eval=FALSE}

# read in the example data
math4 <- readNAEP(filepath='//.../2000 NAEP Mathematics/Grade 4/data/M31NT2AT.dat')
math4a  <- subset(math4, arptsmp == 1)

# Cumulative achievement Levels
achievementLevels(achievementVars="composite_ap", aggregateBy=NULL, data=math4a,
                  defaultConditions=FALSE, weightVar="aorigwt",
                  returnCumulative=TRUE)
```

# References
National Center for Education Statistics. (2014). *Inclusion of Special-Needs Students.* Washington, DC: Author. Retrieved November 28, 2016 from \url{https:
//nces.ed.gov/nationsreportcard/about/inclusion.aspx}.
